### ISSUE TITLE
Load tweaks

### ISSUE THREAD

**Issue by vojkan069** [pwn20wndstuff/pwn20wndstuff.github.io#2]
When load tweaks are on in uncover seetigns my iphone reboot
When is turn off its ok and working 
Iphone x
Ios 14.2
Uncover v 6.0.0

**Comment by SofianeDmt** [comment]
@pwn20wndstuff i have iPhone 12 on iOS 14.4 and waiting a jailbreak uncover compatibility. Still 14.4 on my iPhone 12 or upgrade 14.5.1? Thank bro!
